# Generated by Django 4.1.7 on 2023-03-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
